spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/db_payment
    username: usr_payment
    password: pass_payment
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090
  servlet:
    context-path: /api